Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace u21635618HW03.Models
{
    public class FileModel
    {
    
        [Display(Name = "File Name")]
        public string FileName { get; set; }
        
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }
    }
}

Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using u21635618HW03.Models;

namespace u21635618HW03.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("/Media/Documents"));


            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath)});
            }


            return View(files);
        }
        public FileResult DownloadFile(string fileName )
        {



            string path = Server.MapPath("~/Media/Documents") + "/" + fileName;


            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {

            string path = Server.MapPath("~/Media/Documents")  + "/" + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
    }

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace u21635618HW03.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
            

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file, string Option) 
        {

            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileName(file.FileName);
                string filepath = Path.Combine(Server.MapPath("/Media/" + Option), filename);
                file.SaveAs(filepath);


                //ViewBag message becomes null because of redirection
                //ViewBag.message = "File Uploaded Successfully! " + Option;
            }
            else
            {
                return HttpNotFound("You have not chosen a file.");

                
            }
                return RedirectToAction("Index");
            
        }
        public ActionResult About()
        {


            return View();
        }
    }
}

Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using u21635618HW03.Models;

namespace u21635618HW03.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {

            string[] filePaths = Directory.GetFiles(Server.MapPath("/Media/Images"));


            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath)});
            }

            return View(files);
           
        }
        public FileResult DownloadImage(string fileName)
        {



            string path = Server.MapPath("~/Media/Images/") +  fileName;


            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteImage(string fileName)
        {

            string path = Server.MapPath("~/Media/Images/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using u21635618HW03.Models;

namespace u21635618HW03.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("/Media/Videos"));


            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }
        public FileResult DownloadVideo(string fileName )
        {



            string path = Server.MapPath("~/Media/Videos/")  + fileName;


            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteVideo(string fileName )
        {

            string path = Server.MapPath("~/Media/Videos/")+ fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);

            return RedirectToAction("Index");
        }
    }
}

Views/File/Index.cshtml
@using u21635618HW03.Models
@model List<FileModel>
@{
    ViewBag.Title = "Files";
}

<h1 style="font-weight:normal">Documents of any file type</h1>
<h4 style="font-weight:normal"> ----------"Media/Documents/" folder</h4>
<div class="container" style="background-color:lightcyan;">
    <div style="height: 400px; overflow: auto;">
        <div class="well-sm">
            <table class="table table-condensed "style="margin-top:50px;">
                <thead style="position:sticky; background-color:black;">
                    <tr style="color:white;background-color:black" class="auto-style">
                        <th class="col-lg-6">File Name</th>
                        <th class="col-lg-4">DOWNLOAD OPTION</th>
                        <th>&nbsp;</th>
                        <th class="col-lg-2">DELETE OPTION</th>
                    </tr>
                </thead>
                @foreach (FileModel file in Model)
                {
                    <tr>

                        <td>@file.FileName</td>
                        <td>
                            <button style=" background-color:green; margin-left:25px;">
                                @Html.ActionLink("Download", "DownloadFile",
                                 new { fileName = file.FileName},
                                  new { @style = "color:white;" })
                            </button>
                        </td>
                        <td>&nbsp;</td>
                        <td>
                            <button style=" background-color:red;margin-left:25px;">
                                @Html.ActionLink("DELETE", "DeleteFile",
                               new { fileName = file.FileName },
                               new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                            </button>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<h1 style="font-weight:normal">About</h1>
<h4 style="font-weight:normal"> Inganathi Jacobs' Biography</h4>
<div style="background-color:lightcyan;" class="container">
    <div class="row">
        <div class="col-sm-12 col-lg-6 ">
            <br /><br />
            <h4 style=" margin-top: 10px;">Inganathi Jacobs</h4>
            <p>
                Inganathi Jacobs is a student that is studying towards a BSc Information Science degree at the University of Pretoria.
                She was born and bred in East London, Eastern Cape and only moved to Pretoria in 2021, to begin her University studies.With no experience in coding, in 2021 she  worked towards a BSc Information and Knowledge Systems degree.However,later that year she realised that the computer science part of that degree was not for her and she preffered the informatics side.In 2022 ,she transferred to BSc Information Science in which she has been enjoying.Inganathi enjoys finding out how system works and creating them.
            </p>
        </div>
        <div class="col-sm-12 col-lg-6 ">

            <div class="card" >
                <img src="~/Media/Inganathi.jpg" alt="Inganathi's picture" style="width: 50%; margin-bottom: 50px; margin-top: 50px;">

            </div>

        </div>


    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

}



<h1 style="font-weight:normal">Media Selector</h1>
<h4 style="font-weight:normal"> Choose Media </h4>
<div style="background-color:lightcyan;" class="container">
    <div class="row">
        <div class="col-sm-12 col-lg-6 col-xl-6 col-md-12">
            <h3 style="margin-top:25px; "> Description</h3>
            <p>
                The Home page has a form where you will need to select whether you want to
                upload a file, image, or video. You will then be able to select the file on your device which will
                then be uploaded on submit of the form.
                The Files page displays a list of all the files that you have uploaded with the
                functionality to delete and download the file.
                The Images page displays all the images (which are viewable) that
                you uploaded, in an orderly way with the functionality to delete and download the images.
                The Videos page displays all the videos (which are playable) that
                you uploaded in an orderly way, with the functionality to delete and download the videos.
                The About Me page has a biography about Inganathi Jacobs and her picture.
            </p>
        </div>
        <div class="col-sm-12 col-lg-6 ">
            <h3 style="margin-top:15px; ">Option Selection</h3><br />

            @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div>
                    <label style="font-weight:normal">Document</label><input type="radio" name="Option" value="Documents" /><br />
                    <label style="font-weight:normal">Image</label><input type="radio" name="Option" value="Images" /><br />
                    <label style="font-weight:normal">Video</label><input type="radio" name="Option" value="Videos" /><br /><br />

                </div>

                @Html.TextBox("file", "", new { type = "file", name = "file" })
                <br />
                <input type="submit" value="Submit"/>
             

            }
          

        </div>


    </div>
</div>

Views/Image/Index.cshtml
@using u21635618HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}
<head>
    @*link for fancybox*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <link rel="stylesheet" href="style.css">
</head>

<style type="text/css">
    .grid {
        display: inline-block;
        grid-template-columns: repeat(3, 1fr);
        grid-gap: 10px;
    }

    .gallery {
        margin: 5px;
        border: 1px solid #ccc;
        width: 10px;
        height: 160px;
        display: inline-block;
    }

    img {
        width: 180px;
        height: 200px;
    }

    .column {
        margin: 0px;
        float: left;
        width: 25%;
        padding: 5px;
        background-color: lightcyan;
        /*border:1px solid black;*/
    }

    .row {
        background-color: lightcyan;
    }
</style>

<body>
    <h1 style="font-weight:normal">Images of any file type</h1>
    <h4 style="font-weight:normal"> ----------"Media/Images/" folder </h4>
    <div class="container">
        <div class="row">

            @foreach (FileModel file in Model)
            {

                <div class="col-xs-4" style="margin-top: 20px; margin-bottom: 20px; ">
                    <a data-fancybox="gallery" href="~/Media/Images/@file.FileName"><img  src="~/Media/Images/@file.FileName" alt="Image not found" style="position:relative"></a>

                    <h5> @file.FileName</h5>
                    <button class="butt" style=" background-color:green; margin-right: 20px;">
                        @Html.ActionLink("Download", "DownloadImage",
                         new { fileName = file.FileName},
                         new { @style = "color:white;" })
                    </button>

                    <button style=" background-color:red;">
                        @Html.ActionLink("DELETE", "DeleteImage",
                       new { fileName = file.FileName},
                       new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                    </button>

                </div>
            }


        </div>
    </div>
    @*for the fancybox*@
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*<title>@ViewBag.Title - My ASP.NET Application</title>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "File")</li>
                    <li>@Html.ActionLink("Images", "Index", "Image")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Video")</li>
                    <li>@Html.ActionLink("About Me", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - INF 272 Homework 3</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Video/Index.cshtml
@using u21635618HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Index";
}
<head>
    @*link for fancybox*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <link rel="stylesheet" href="style.css">
</head>

<style type="text/css">
    .grid {
        display: inline-block;
        grid-template-columns: repeat(3, 1fr);
        grid-gap: 10px;
    }

    .gallery {
        margin: 5px;
        border: 1px solid #ccc;
        width: 10px;
        height: 160px;
        display: inline-block;
    }

    img {
        width: 50px;
        height: 200px;
    }

    .column {
        margin: 0px;
        float: left;
        width: 25%;
        padding: 5px;
        background-color: lightcyan;
        /*border:1px solid black;*/
    }

    .row {
        background-color: lightcyan;
    }
</style>

<body>
    <h1 style="font-weight:normal">Video Files</h1>
    <h4 style="font-weight:normal"> ----------"Media/Videos/" folder </h4>
    <div class="container">
        <div class="row">

            @foreach (FileModel file in Model)
            {

                <div class="col-xs-4" style="margin-top: 20px; margin-bottom: 20px;">
                    <a data-fancybox="gallery" href="~/Media/Videos/@file.FileName"><video style="width: 18rem; height:200px" class="card-img-top"  controls><source src="~/Media/Videos/@file.FileName" type="video/mp4" /></video></a>

                    <h5> @file.FileName</h5>
                    <button class="butt" style=" background-color:green; margin-right: 20px;">
                        @Html.ActionLink("Download", "DownloadVideo",
                         new { fileName = file.FileName },
                         new { @style = "color:white;" })
                    </button>

                    <button style=" background-color:red;">
                        @Html.ActionLink("DELETE", "DeleteVideo",
                       new { fileName = file.FileName },
                       new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                    </button>

                </div>
            }


        </div>
    </div>
    @*for the fancybox*@
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
</body>